#version: 2.1
#
#commands:
#
#  mvn_jar_deploy:
#    steps:
#      - checkout
#      - run:
#          name: Adjust pom version
#          command: |
#            .circleci/adjust-pom-version.sh
#      - restore_cache:
#          keys:
#            - v1-dependencies-{{ checksum "pom.xml" }}
#      - run:
#          name: Run Maven Jar Deploy
#          command: |
#            mvn -s .circleci/mvn-settings.xml -T4 flatten:flatten jar:jar deploy:deploy
#      - save_cache:
#          paths:
#            - ~/.m2
#          key: v1-dependencies-{{ checksum "pom.xml" }}
#
#jobs:
#  mvn_test:
#    executor: cimg/openjdk:17.0.14
#    steps:
#      - mvn_verify
#
#  mvn_deploy:
#    executor: cimg/openjdk:17.0.14
#    steps:
#      - mvn_jar_deploy
#
#workflows:
#  test_only:
#    jobs:
#      - mvn_test:
#          context: qqq-maven-registry-credentials
#          filters:
#            branches:
#              ignore: /(dev|integration.*)/
#            tags:
#              ignore: /(version|snapshot)-.*/
#
#  deploy:
#    jobs:
#      - mvn_deploy:
#          context: qqq-maven-registry-credentials
#          filters:
#            branches:
#              only: /(dev|integration.*)/
#            tags:
#              only: /(version|snapshot)-.*/

version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:17-jdk

jobs:
  verify:
    executor: java-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-maven-cache-{{ checksum "pom.xml" }}
      - run:
          name: Verify with Maven
          command: mvn verify
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          paths:
            - ~/.m2/repository
          key: v1-maven-cache-{{ checksum "pom.xml" }}

  deploy:
    executor: java-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-maven-cache-{{ checksum "pom.xml" }}
      - run:
          name: Deploy with Maven
          command: mvn deploy
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          paths:
            - ~/.m2/repository
          key: v1-maven-cache-{{ checksum "pom.xml" }}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - verify:
          context: qqq-maven-registry-credentials
          filters:
            branches:
              ignore: main
      - deploy:
          context: qqq-maven-registry-credentials
          filters:
            branches:
              only: main